fix AttributeError raised by numpy
Trying to fix the following error:
```
Traceback (most recent call last):
  File "/kaggle/working/yolov5-crowdhuman/test.py", line 309, in <module>
    test(opt.data,
  File "/kaggle/working/yolov5-crowdhuman/test.py", line 89, in test
    dataloader = create_dataloader(path, imgsz, batch_size, gs, opt, pad=0.5, rect=True,
  File "/kaggle/working/yolov5-crowdhuman/utils/datasets.py", line 63, in create_dataloader
    dataset = LoadImagesAndLabels(path, imgsz, batch_size,
  File "/kaggle/working/yolov5-crowdhuman/utils/datasets.py", line 405, in __init__
    bi = np.floor(np.arange(n) / batch_size).astype(np.int)  # batch index
  File "/opt/conda/lib/python3.10/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?
```